import os
import uuid
import urllib.parse
from datetime import datetime, timedelta
from typing import Optional, Dict, Any
import httpx
from jose import jwt, JWTError

from backend.services.auth_service import (
    SECRET_KEY,
    ALGORITHM,
    get_db,
    get_password_hash,
    create_access_token,
    create_refresh_token,
)

# Environment variables
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "").strip()
GOOGLE_CALLBACK_URL = os.environ.get(
    "GOOGLE_CALLBACK_URL", "http://localhost:8000/auth/google/callback"
).strip()

GITHUB_CLIENT_ID = os.environ.get("GITHUB_CLIENT_ID", "").strip()
GITHUB_CLIENT_SECRET = os.environ.get("GITHUB_CLIENT_SECRET", "").strip()
GITHUB_CALLBACK_URL = os.environ.get(
    "GITHUB_CALLBACK_URL", "http://localhost:8000/auth/github/callback"
).strip()

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173").rstrip("/")


def is_google_configured() -> bool:
    """Return True if Google OAuth credentials are fully provided."""
    # Re-fetch from os.environ to support runtime changes or .env updates
    cid = os.environ.get("GOOGLE_CLIENT_ID", GOOGLE_CLIENT_ID).strip()
    sec = os.environ.get("GOOGLE_CLIENT_SECRET", GOOGLE_CLIENT_SECRET).strip()
    return bool(cid and sec)


def is_github_configured() -> bool:
    """Return True if GitHub OAuth credentials are fully provided."""
    # Re-fetch from os.environ to support runtime changes or .env updates
    cid = os.environ.get("GITHUB_CLIENT_ID", GITHUB_CLIENT_ID).strip()
    sec = os.environ.get("GITHUB_CLIENT_SECRET", GITHUB_CLIENT_SECRET).strip()
    return bool(cid and sec)


def generate_oauth_state(provider: str, redirect_to: str = "/app") -> str:
    """
    Generate a tamper-proof, signed JWT state parameter to prevent CSRF attacks.
    Embeds the provider, redirect target, random nonce, and expiration.
    """
    clean_redirect = redirect_to if (redirect_to.startswith("/") and not redirect_to.startswith("//")) else "/app"
    payload = {
        "action": "oauth_auth",
        "provider": provider.lower(),
        "redirect_to": clean_redirect,
        "nonce": str(uuid.uuid4()),
        "exp": datetime.utcnow() + timedelta(minutes=15),
    }
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def validate_oauth_state(state: str, expected_provider: str) -> Optional[Dict[str, Any]]:
    """
    Validate that the incoming state parameter was generated by this server,
    matches the expected provider, and has not expired.
    """
    try:
        payload = jwt.decode(state, SECRET_KEY, algorithms=[ALGORITHM])
        if payload.get("action") != "oauth_auth":
            return None
        if payload.get("provider") != expected_provider.lower():
            return None
        return payload
    except (JWTError, Exception):
        return None


def get_google_auth_url(state: str) -> str:
    """Generate the Google OAuth 2.0 authorization URL."""
    cid = os.environ.get("GOOGLE_CLIENT_ID", GOOGLE_CLIENT_ID).strip()
    cb_url = os.environ.get("GOOGLE_CALLBACK_URL", GOOGLE_CALLBACK_URL).strip()
    params = {
        "client_id": cid,
        "redirect_uri": cb_url,
        "response_type": "code",
        "scope": "openid email profile",
        "access_type": "offline",
        "prompt": "select_account",
        "state": state,
    }
    return f"https://accounts.google.com/o/oauth2/v2/auth?{urllib.parse.urlencode(params)}"


def get_github_auth_url(state: str) -> str:
    """Generate the GitHub OAuth authorization URL."""
    cid = os.environ.get("GITHUB_CLIENT_ID", GITHUB_CLIENT_ID).strip()
    cb_url = os.environ.get("GITHUB_CALLBACK_URL", GITHUB_CALLBACK_URL).strip()
    params = {
        "client_id": cid,
        "redirect_uri": cb_url,
        "scope": "read:user user:email",
        "state": state,
    }
    return f"https://github.com/login/oauth/authorize?{urllib.parse.urlencode(params)}"


async def exchange_google_code_for_user(code: str) -> Dict[str, Any]:
    """
    Exchange authorization code with Google token endpoint and retrieve user profile.
    Validates that the email is verified.
    """
    cid = os.environ.get("GOOGLE_CLIENT_ID", GOOGLE_CLIENT_ID).strip()
    sec = os.environ.get("GOOGLE_CLIENT_SECRET", GOOGLE_CLIENT_SECRET).strip()
    cb_url = os.environ.get("GOOGLE_CALLBACK_URL", GOOGLE_CALLBACK_URL).strip()

    token_url = "https://oauth2.googleapis.com/token"
    token_data = {
        "code": code,
        "client_id": cid,
        "client_secret": sec,
        "redirect_uri": cb_url,
        "grant_type": "authorization_code",
    }

    async with httpx.AsyncClient(timeout=15.0) as client:
        token_resp = await client.post(token_url, data=token_data)
        if token_resp.status_code != 200:
            raise ValueError(f"Google token exchange failed: {token_resp.text}")

        token_json = token_resp.json()
        access_token = token_json.get("access_token")
        if not access_token:
            raise ValueError("No access_token returned by Google")

        userinfo_url = "https://www.googleapis.com/oauth2/v3/userinfo"
        userinfo_resp = await client.get(
            userinfo_url, headers={"Authorization": f"Bearer {access_token}"}
        )
        if userinfo_resp.status_code != 200:
            raise ValueError(f"Failed to fetch Google user profile: {userinfo_resp.text}")

        user_data = userinfo_resp.json()
        email = user_data.get("email")
        if not email:
            raise ValueError("Google account has no associated email address")

        email_verified = user_data.get("email_verified", False)
        if not email_verified:
            raise ValueError("Google email address is not verified")

        return {
            "provider": "google",
            "provider_id": str(user_data.get("sub")),
            "email": email.strip().lower(),
            "name": user_data.get("name") or email.split("@")[0],
            "avatar_url": user_data.get("picture"),
        }


async def exchange_github_code_for_user(code: str) -> Dict[str, Any]:
    """
    Exchange authorization code with GitHub token endpoint and retrieve user profile.
    If primary email is private, fetches verified emails from /user/emails.
    """
    cid = os.environ.get("GITHUB_CLIENT_ID", GITHUB_CLIENT_ID).strip()
    sec = os.environ.get("GITHUB_CLIENT_SECRET", GITHUB_CLIENT_SECRET).strip()
    cb_url = os.environ.get("GITHUB_CALLBACK_URL", GITHUB_CALLBACK_URL).strip()

    token_url = "https://github.com/login/oauth/access_token"
    token_data = {
        "client_id": cid,
        "client_secret": sec,
        "code": code,
        "redirect_uri": cb_url,
    }

    async with httpx.AsyncClient(timeout=15.0) as client:
        token_resp = await client.post(
            token_url,
            data=token_data,
            headers={"Accept": "application/json"},
        )
        if token_resp.status_code != 200:
            raise ValueError(f"GitHub token exchange failed: {token_resp.text}")

        token_json = token_resp.json()
        access_token = token_json.get("access_token")
        if not access_token:
            err_desc = token_json.get("error_description", token_resp.text)
            raise ValueError(f"GitHub authorization failed: {err_desc}")

        user_url = "https://api.github.com/user"
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "Fluxline-Migration-Engine",
        }
        user_resp = await client.get(user_url, headers=headers)
        if user_resp.status_code != 200:
            raise ValueError(f"Failed to fetch GitHub profile: {user_resp.text}")

        user_data = user_resp.json()
        email = user_data.get("email")

        # If user's email is private, query /user/emails
        if not email:
            emails_resp = await client.get("https://api.github.com/user/emails", headers=headers)
            if emails_resp.status_code == 200:
                emails_list = emails_resp.json()
                # Find primary verified email
                for entry in emails_list:
                    if entry.get("primary") and entry.get("verified"):
                        email = entry.get("email")
                        break
                # Fallback to any verified email
                if not email:
                    for entry in emails_list:
                        if entry.get("verified"):
                            email = entry.get("email")
                            break

        if not email:
            raise ValueError("No verified email associated with this GitHub account")

        return {
            "provider": "github",
            "provider_id": str(user_data.get("id")),
            "email": email.strip().lower(),
            "name": user_data.get("name") or user_data.get("login") or email.split("@")[0],
            "avatar_url": user_data.get("avatar_url"),
        }


def sync_oauth_user(provider_user: Dict[str, Any]) -> Dict[str, Any]:
    """
    Find or create user in the database.
    - If user with (oauth_provider, oauth_provider_id) exists, login.
    - Else if user with email exists, link OAuth details and login.
    - Else, create new organization and user with role='Admin' and a secure random password hash.
    Returns: { "user": dict, "access_token": str, "refresh_token": str }
    """
    provider = provider_user["provider"]
    provider_id = str(provider_user["provider_id"])
    email = provider_user["email"]
    name = provider_user.get("name")
    avatar_url = provider_user.get("avatar_url")

    conn = get_db()
    cursor = conn.cursor()

    # 1. Search by provider and provider_id
    cursor.execute(
        "SELECT * FROM users WHERE oauth_provider = ? AND oauth_provider_id = ?",
        (provider, provider_id),
    )
    user_row = cursor.fetchone()

    # 2. If not found, search by verified email
    if not user_row and email:
        cursor.execute("SELECT * FROM users WHERE LOWER(email) = ?", (email,))
        user_row = cursor.fetchone()

        if user_row:
            # Link existing user account to provider
            cursor.execute(
                """UPDATE users SET 
                    oauth_provider = COALESCE(oauth_provider, ?),
                    oauth_provider_id = COALESCE(oauth_provider_id, ?),
                    avatar_url = COALESCE(avatar_url, ?),
                    name = COALESCE(name, ?)
                   WHERE id = ?""",
                (provider, provider_id, avatar_url, name, user_row["id"]),
            )
            conn.commit()
            cursor.execute("SELECT * FROM users WHERE id = ?", (user_row["id"],))
            user_row = cursor.fetchone()

    # 3. If still not found, create new user and organization
    if not user_row:
        org_id = str(uuid.uuid4())
        user_id = str(uuid.uuid4())
        org_name = f"{(name or email.split('@')[0])}'s Workspace"

        cursor.execute(
            "INSERT INTO organizations (id, name) VALUES (?, ?)", (org_id, org_name)
        )

        # Generate an unguessable bcrypt hash for OAuth users to satisfy the SQLite NOT NULL constraint
        unusable_pw_hash = get_password_hash(f"oauth_{uuid.uuid4()}_{uuid.uuid4()}")

        cursor.execute(
            """INSERT INTO users 
               (id, org_id, email, hashed_password, role, oauth_provider, oauth_provider_id, avatar_url, name)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                user_id,
                org_id,
                email,
                unusable_pw_hash,
                "Admin",
                provider,
                provider_id,
                avatar_url,
                name,
            ),
        )
        conn.commit()
        cursor.execute("SELECT * FROM users WHERE id = ?", (user_id,))
        user_row = cursor.fetchone()

    user_dict = dict(user_row)
    conn.close()

    # 4. Generate access token and refresh token using existing auth infrastructure
    access_token = create_access_token(
        data={"sub": user_dict["id"], "org_id": user_dict["org_id"], "role": user_dict["role"]}
    )
    refresh_token = create_refresh_token(user_dict["id"])

    return {
        "user": user_dict,
        "access_token": access_token,
        "refresh_token": refresh_token,
    }
