lines = open('frontend/src/pages/NewMigration.jsx', 'r').readlines()
idx_start = -1
for i, l in enumerate(lines):
    if 'AI Transcompiler Enabled' in l:
        idx_start = i
        break

lines = lines[:idx_start+2]
lines.append('                            {options.auto_approve_objects \n')
lines.append('                              ? <span className="text-status-error font-bold">Auto-Approve Enabled: Translations will be executed automatically!</span> \n')
lines.append('                              : "Procedures/Views will pause in report for manual human verification code approvals."}\n')
lines.append('                          </span>\n')
lines.append('                        </div>\n')
lines.append('                      </div>\n')
lines.append('                    )}\n')
lines.append('                  </div>\n')
lines.append('                </div>\n')
lines.append('\n')
lines.append('                {/* Ignite Launcher Button */}\n')
lines.append('                <div className="pt-4 border-t border-border-default shrink-0">\n')
lines.append('                  <motion.button \n')
lines.append('                    whileTap={shouldReduceMotion ? {} : { scale: 0.98 }}\n')
lines.append('                    disabled={isSubmitting || (!options.migrate_all_tables && (!options.selected_tables || options.selected_tables.length === 0))}\n')
lines.append('                    className="w-full py-4 rounded-xl text-xs font-mono font-bold uppercase tracking-widest bg-success hover:bg-success/90 shadow-[0_0_20px_var(--color-success-muted)] text-white flex items-center justify-center space-x-2 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"\n')
lines.append('                    onClick={submitMigration}\n')
lines.append('                  >\n')
lines.append('                    <span>{isSubmitting ? \'Initializing Workspace...\' : \'Ignite Migration Pipeline\'}</span>\n')
lines.append('                    <ArrowRight className="w-4 h-4 text-white" />\n')
lines.append('                  </motion.button>\n')
lines.append('                </div>\n')
lines.append('              </div>\n')
lines.append('            </motion.div>\n')
lines.append('          )}\n')
lines.append('        </AnimatePresence>\n')
lines.append('      </div>\n')
lines.append('\n')
lines.append('      {/* Schema Visualizer Modal */}\n')
lines.append('      <AnimatePresence>\n')
lines.append('        {showSchemaVisualizer && (\n')
lines.append('          <motion.div\n')
lines.append('            initial={{ opacity: 0 }}\n')
lines.append('            animate={{ opacity: 1 }}\n')
lines.append('            exit={{ opacity: 0 }}\n')
lines.append('            transition={{ duration: 0.2 }}\n')
lines.append('            className="fixed inset-0 z-50 flex items-center justify-center p-8 bg-bg-canvas/80 backdrop-blur-sm"\n')
lines.append('          >\n')
lines.append('            <motion.div\n')
lines.append('              initial={{ scale: 0.95, opacity: 0 }}\n')
lines.append('              animate={{ scale: 1, opacity: 1 }}\n')
lines.append('              exit={{ scale: 0.95, opacity: 0 }}\n')
lines.append('              transition={{ duration: 0.2 }}\n')
lines.append('              className="w-full h-full max-w-7xl max-h-[90vh] bg-bg-panel border border-border-default rounded-xl shadow-2xl overflow-hidden"\n')
lines.append('            >\n')
lines.append('              <SchemaVisualizer\n')
lines.append('                sourceConfig={source}\n')
lines.append('                standalone={false}\n')
lines.append('                selectedTables={options.selected_tables || []}\n')
lines.append('                onToggleTable={(tableName) => {\n')
lines.append('                  setOptions(prev => {\n')
lines.append('                    const current = prev.selected_tables || [];\n')
lines.append('                    if (current.includes(tableName)) {\n')
lines.append('                      return { ...prev, selected_tables: current.filter(t => t !== tableName) }\n')
lines.append('                    } else {\n')
lines.append('                      return { ...prev, selected_tables: [...current, tableName] }\n')
lines.append('                    }\n')
lines.append('                  });\n')
lines.append('                }}\n')
lines.append('                onClose={() => setShowSchemaVisualizer(false)}\n')
lines.append('              />\n')
lines.append('            </motion.div>\n')
lines.append('          </motion.div>\n')
lines.append('        )}\n')
lines.append('      </AnimatePresence>\n')
lines.append('    </div>\n')
lines.append('  )\n')
lines.append('}\n')
with open('frontend/src/pages/NewMigration.jsx', 'w') as f:
    f.writelines(lines)
