import oracledb
import random
import string
import time

def random_string(length):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def generate_data():
    conn = oracledb.connect(user="pdbadmin", password="Oracle123", dsn="localhost:1521/ORACLEDB")
    cursor = conn.cursor()
    
    # Create table
    print("Creating tables...")
    try:
        cursor.execute("DROP TABLE orders CASCADE CONSTRAINTS")
    except oracledb.DatabaseError:
        pass

    try:
        cursor.execute("DROP TABLE customers CASCADE CONSTRAINTS")
    except oracledb.DatabaseError:
        pass
        
    cursor.execute("""
        CREATE TABLE customers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name VARCHAR2(50),
            last_name VARCHAR2(50),
            email VARCHAR2(100),
            created_at DATE DEFAULT SYSDATE
        )
    """)
    
    cursor.execute("""
        CREATE TABLE orders (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id NUMBER,
            amount NUMBER(10, 2),
            status VARCHAR2(20),
            order_date DATE DEFAULT SYSDATE,
            CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
        )
    """)
    
    print("Generating customer data (20,000 rows)...")
    customers = []
    for i in range(20000):
        customers.append((
            random_string(10),
            random_string(10),
            f"{random_string(8)}@example.com"
        ))
        
    cursor.executemany("""
        INSERT INTO customers (first_name, last_name, email)
        VALUES (:1, :2, :3)
    """, customers)
    conn.commit()
    
    print("Generating order data (80,000 rows)...")
    statuses = ['PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
    orders = []
    for i in range(80000):
        orders.append((
            random.randint(1, 20000),
            round(random.uniform(10.0, 1000.0), 2),
            random.choice(statuses)
        ))
        
    chunk_size = 10000
    for i in range(0, len(orders), chunk_size):
        chunk = orders[i:i+chunk_size]
        cursor.executemany("""
            INSERT INTO orders (customer_id, amount, status)
            VALUES (:1, :2, :3)
        """, chunk)
    conn.commit()
    
    print("Database generation complete! Created 20,000 customers and 80,000 orders (100K rows total).")
    
    cursor.execute("SELECT COUNT(*) FROM customers")
    cust_count = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(*) FROM orders")
    order_count = cursor.fetchone()[0]
    print(f"Verification: Customers: {cust_count}, Orders: {order_count}, Total: {cust_count + order_count}")
    
    cursor.close()
    conn.close()

if __name__ == "__main__":
    start = time.time()
    generate_data()
    print(f"Time taken: {time.time() - start:.2f} seconds")
