import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { 
  Database, ArrowRight, ShieldCheck, 
  RefreshCw, Zap, ChevronRight,
  Check, Copy, Code2, Cpu, Terminal, Play, Pause,
  Lock, Layers, CheckCircle2, Server, BarChart3,
  ExternalLink, Network, FileCode, CheckCircle, ArrowUpRight
} from 'lucide-react'

// --- Motion Presets ---
const FADE_UP = { 
  initial: { opacity: 0, y: 16 }, 
  whileInView: { opacity: 1, y: 0 }, 
  viewport: { once: true, margin: "-60px" },
  transition: { duration: 0.45, ease: [0.16, 1, 0.3, 1] } 
}

const DIALECT_EXAMPLES = {
  'pg-mysql': {
    from: 'PostgreSQL 16',
    to: 'MySQL 8.0',
    title: 'PostgreSQL → MySQL 8.0',
    sourceCode: `-- PostgreSQL DDL with dialect-specific types
CREATE TABLE user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip_address INET,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);`,
    targetCode: `-- Compiled MySQL 8.0 DDL (AST Translated)
CREATE TABLE user_sessions (
  id VARCHAR(36) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  metadata JSON NOT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) 
    REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`,
    notes: [
      'Remapped UUID → VARCHAR(36) with deterministic format validation',
      'Compiled JSONB → native MySQL JSON column type',
      'Converted INET network type to VARCHAR(45) supporting IPv4/IPv6',
      'Aligned TIMESTAMPTZ → DATETIME(6) with microsecond precision'
    ]
  },
  'mssql-pg': {
    from: 'SQL Server 2022',
    to: 'PostgreSQL 16',
    title: 'SQL Server → PostgreSQL 16',
    sourceCode: `-- SQL Server Schema with IDENTITY & BIT
CREATE TABLE dbo.Orders (
  OrderID INT IDENTITY(1,1) PRIMARY KEY,
  CustomerGUID UNIQUEIDENTIFIER DEFAULT NEWID(),
  IsSettled BIT NOT NULL DEFAULT 0,
  OrderDate DATETIME2(3) NOT NULL,
  TotalAmount MONEY NOT NULL
);`,
    targetCode: `-- Compiled PostgreSQL 16 DDL
CREATE TABLE orders (
  order_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  customer_guid UUID DEFAULT gen_random_uuid(),
  is_settled BOOLEAN NOT NULL DEFAULT FALSE,
  order_date TIMESTAMP(3) NOT NULL,
  total_amount NUMERIC(19,4) NOT NULL
);`,
    notes: [
      'Translated IDENTITY(1,1) → SQL:2008 standard GENERATED ALWAYS AS IDENTITY',
      'Mapped T-SQL BIT → native PostgreSQL BOOLEAN',
      'Preserved DATETIME2(3) precision as TIMESTAMP(3)',
      'Converted MONEY → exact fixed-point NUMERIC(19,4)'
    ]
  },
  'oracle-pg': {
    from: 'Oracle 21c',
    to: 'PostgreSQL 16',
    title: 'Oracle 21c → PostgreSQL 16',
    sourceCode: `-- Oracle 21c DDL with VARCHAR2 & NUMBER
CREATE TABLE HR.EMPLOYEES (
  EMPLOYEE_ID NUMBER(6,0) PRIMARY KEY,
  FIRST_NAME VARCHAR2(20),
  LAST_NAME VARCHAR2(25) NOT NULL,
  SALARY NUMBER(8,2),
  HIRE_DATE DATE DEFAULT SYSDATE NOT NULL
);`,
    targetCode: `-- Compiled PostgreSQL 16 DDL
CREATE TABLE employees (
  employee_id INT PRIMARY KEY,
  first_name VARCHAR(20),
  last_name VARCHAR(25) NOT NULL,
  salary NUMERIC(8,2),
  hire_date DATE DEFAULT CURRENT_DATE NOT NULL
);`,
    notes: [
      'Mapped NUMBER(6,0) integers → PostgreSQL INT',
      'Normalized Oracle VARCHAR2 → standard ANSI VARCHAR',
      'Converted NUMBER(8,2) → NUMERIC(8,2) floating precision',
      'Substituted SYSDATE → ANSI CURRENT_DATE standard'
    ]
  },
  'mysql-pg': {
    from: 'MySQL 8.0',
    to: 'PostgreSQL 16',
    title: 'MySQL 8.0 → PostgreSQL 16',
    sourceCode: `-- MySQL DDL with AUTO_INCREMENT & ENUM
CREATE TABLE inventory_items (
  item_id INT AUTO_INCREMENT PRIMARY KEY,
  status ENUM('draft', 'published', 'archived') DEFAULT 'draft',
  attributes JSON,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);`,
    targetCode: `-- Compiled PostgreSQL 16 DDL
CREATE TYPE item_status_enum AS ENUM ('draft', 'published', 'archived');

CREATE TABLE inventory_items (
  item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status item_status_enum DEFAULT 'draft',
  attributes JSONB,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Generated trigger for ON UPDATE timestamp synchronization`,
    notes: [
      'Extracted inline MySQL ENUM → dedicated PostgreSQL ENUM type',
      'Upgraded MySQL text JSON → binary indexed JSONB',
      'Generated trigger procedure to replicate ON UPDATE timestamp behavior'
    ]
  }
}

export default function Landing() {
  const [activeDialect, setActiveDialect] = useState('pg-mysql')
  const [activeWorkbenchTab, setActiveWorkbenchTab] = useState('stream')
  const [copiedCli, setCopiedCli] = useState(false)
  const [simulating, setSimulating] = useState(true)
  const [simulatedProgress, setSimulatedProgress] = useState(78)
  const [simulatedRows, setSimulatedRows] = useState(184291044)

  useEffect(() => {
    if (!simulating) return
    const interval = setInterval(() => {
      setSimulatedProgress(p => (p >= 99 ? 74 : p + 1))
      setSimulatedRows(r => r + 34200)
    }, 1200)
    return () => clearInterval(interval)
  }, [simulating])

  const copyCliCommand = () => {
    navigator.clipboard.writeText('npx @fluxline/cli verify --source "postgres://..." --target "mysql://..."')
    setCopiedCli(true)
    setTimeout(() => setCopiedCli(false), 2000)
  }

  return (
    <div className="w-full flex flex-col font-sans selection:bg-indigo-500/30 selection:text-white pb-24 text-zinc-200">
      
      {/* ================= HERO SECTION ================= */}
      <section className="relative pt-20 pb-16 md:pt-32 md:pb-24 px-6 overflow-hidden">
        <div className="max-w-5xl mx-auto relative z-10 flex flex-col items-center text-center">
          
          {/* Engineering Release Pill */}
          <motion.div 
            initial={{ opacity: 0, y: -8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="mb-6 inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-zinc-900/90 border border-zinc-800 text-xs font-mono text-zinc-300 shadow-sm hover:border-zinc-700 transition-colors"
          >
            <span className="flex h-2 w-2 relative">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500"></span>
            </span>
            <span className="text-zinc-300 font-semibold">Engine v2.4</span>
            <span className="text-zinc-600">|</span>
            <span className="text-zinc-400">Zero-Loss Keyset Chunking & Oracle 21c Engine</span>
          </motion.div>

          {/* Master Headline */}
          <motion.h1 
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.05, ease: [0.16, 1, 0.3, 1] }}
            className="font-sans text-[36px] sm:text-[46px] md:text-[54px] font-bold text-white tracking-tight leading-[1.12] mb-6 max-w-4xl"
          >
            Deterministic database migration. <br className="hidden sm:block" />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-zinc-100 via-indigo-200 to-indigo-400">
              Zero downtime. Zero guesswork.
            </span>
          </motion.h1>

          {/* Subtitle */}
          <motion.p 
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
            className="font-sans text-base md:text-lg text-zinc-400 max-w-2xl mb-8 leading-relaxed"
          >
            Compile-time DDL translation across PostgreSQL, MySQL, SQL Server, and Oracle. Stream gigabytes with keyset chunking, automated FK graph sequencing, and byte-for-byte checksum parity.
          </motion.p>

          {/* CTAs */}
          <motion.div 
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
            className="flex flex-col sm:flex-row items-center gap-3.5 w-full sm:w-auto"
          >
            <Link 
              to="/app/new" 
              className="w-full sm:w-auto px-6 py-3 rounded-lg bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white font-sans text-sm font-semibold transition-all shadow-sm flex items-center justify-center space-x-2"
            >
              <span>Start New Migration</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
            <Link 
              to="/sandbox" 
              className="w-full sm:w-auto px-6 py-3 rounded-lg bg-zinc-900 hover:bg-zinc-800 text-zinc-200 font-sans text-sm font-medium border border-zinc-800 transition-all flex items-center justify-center space-x-2 shadow-sm"
            >
              <Code2 className="w-4 h-4 text-zinc-400" />
              <span>Open DDL Sandbox</span>
            </Link>
          </motion.div>

          {/* Trust Specs Strip */}
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.6 }}
            className="mt-10 flex flex-wrap justify-center items-center gap-6 text-xs text-zinc-400 border-t border-zinc-800/80 pt-6 max-w-3xl font-mono"
          >
            <div className="flex items-center space-x-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
              <span>Compiled AST Translation</span>
            </div>
            <div className="flex items-center space-x-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
              <span>Keyset Index Streaming (35k+ rows/s)</span>
            </div>
            <div className="flex items-center space-x-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
              <span>Byte-for-Byte SHA256 Verification</span>
            </div>
          </motion.div>

          {/* ================= INTERACTIVE WORKBENCH TELEMETRY ================= */}
          <motion.div 
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.25, ease: [0.16, 1, 0.3, 1] }}
            className="mt-12 w-full text-left"
          >
            <div className="w-full rounded-xl border border-zinc-800 bg-[#101014] shadow-2xl overflow-hidden ring-1 ring-white/[0.04]">
              
              {/* Workbench Header & Tabs */}
              <div className="border-b border-zinc-800 flex flex-wrap items-center justify-between px-4 py-2.5 bg-zinc-900/60 gap-3">
                
                {/* Tabs */}
                <div className="flex items-center space-x-1">
                  <button
                    onClick={() => setActiveWorkbenchTab('stream')}
                    className={`px-3 py-1.5 rounded-md text-xs font-mono font-medium transition-all flex items-center space-x-2 ${
                      activeWorkbenchTab === 'stream' 
                        ? 'bg-zinc-800 text-white shadow-sm border border-zinc-700' 
                        : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/40'
                    }`}
                  >
                    <Zap className="w-3.5 h-3.5 text-indigo-400" />
                    <span>Live Keyset Stream</span>
                  </button>

                  <button
                    onClick={() => setActiveWorkbenchTab('schema')}
                    className={`px-3 py-1.5 rounded-md text-xs font-mono font-medium transition-all flex items-center space-x-2 ${
                      activeWorkbenchTab === 'schema' 
                        ? 'bg-zinc-800 text-white shadow-sm border border-zinc-700' 
                        : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/40'
                    }`}
                  >
                    <Code2 className="w-3.5 h-3.5 text-emerald-400" />
                    <span>AST Schema Diff</span>
                  </button>

                  <button
                    onClick={() => setActiveWorkbenchTab('parity')}
                    className={`px-3 py-1.5 rounded-md text-xs font-mono font-medium transition-all flex items-center space-x-2 ${
                      activeWorkbenchTab === 'parity' 
                        ? 'bg-zinc-800 text-white shadow-sm border border-zinc-700' 
                        : 'text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800/40'
                    }`}
                  >
                    <ShieldCheck className="w-3.5 h-3.5 text-sky-400" />
                    <span>Parity & Checksum Matrix</span>
                  </button>
                </div>

                {/* Right Status / Control */}
                <div className="flex items-center space-x-2.5">
                  <div className="hidden sm:flex items-center space-x-1.5 px-2.5 py-1 rounded bg-zinc-950/80 border border-zinc-800 text-[11px] font-mono text-zinc-300">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                    <span>CDC Active • Lag: 2.1ms</span>
                  </div>

                  <button 
                    onClick={() => setSimulating(!simulating)} 
                    className="text-xs font-mono text-zinc-300 hover:text-white flex items-center space-x-1 bg-zinc-800/80 hover:bg-zinc-700 px-2.5 py-1 rounded border border-zinc-700/60 transition-colors cursor-pointer"
                  >
                    {simulating ? <Pause className="w-3 h-3 text-amber-400" /> : <Play className="w-3 h-3 text-emerald-400" />}
                    <span>{simulating ? 'Pause' : 'Resume'}</span>
                  </button>
                </div>
              </div>

              {/* Workbench Tab Content */}
              <div className="p-5 md:p-6">
                
                {/* TAB 1: LIVE STREAM ENGINE */}
                {activeWorkbenchTab === 'stream' && (
                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
                    
                    <div className="lg:col-span-2 space-y-4">
                      <div className="flex flex-wrap items-center justify-between gap-2 pb-1">
                        <div>
                          <div className="flex items-center space-x-2">
                            <span className="text-white font-semibold text-sm">Enterprise Core Cluster Migration</span>
                            <span className="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 text-zinc-300 text-[10px] font-mono">JOB-8941</span>
                          </div>
                          <p className="text-zinc-400 text-xs mt-0.5">PostgreSQL 16 (Primary us-east-1) ➔ MySQL 8.0 (Aurora Multi-AZ)</p>
                        </div>
                        <span className="text-emerald-400 font-mono text-xs font-medium bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                          {simulating ? 'Streaming (8 Keyset Workers)' : 'Paused'}
                        </span>
                      </div>

                      {/* Progress Bar & Rate Stats */}
                      <div className="p-4 rounded-lg bg-zinc-950/70 border border-zinc-800 space-y-2.5">
                        <div className="flex justify-between items-center text-xs font-mono">
                          <span className="text-zinc-400">Total Rows Processed</span>
                          <span className="text-zinc-100 font-semibold">{simulatedProgress}% ({simulatedRows.toLocaleString()} / 236,000,000)</span>
                        </div>
                        <div className="w-full h-2 rounded-full bg-zinc-800 overflow-hidden relative">
                          <motion.div 
                            className="h-full bg-indigo-500 rounded-full" 
                            animate={{ width: `${simulatedProgress}%` }}
                            transition={{ duration: 0.4 }}
                          />
                        </div>
                        <div className="flex justify-between items-center text-[11px] text-zinc-400 font-mono pt-1">
                          <span>Throughput: 34,200 rows/sec</span>
                          <span>Est. Remaining: 1m 48s</span>
                          <span>Failed Chunks: 0</span>
                        </div>
                      </div>

                      {/* Active Tables Queue Grid */}
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
                        <div className="p-2.5 rounded bg-zinc-900/60 border border-zinc-800">
                          <div className="text-zinc-400 text-[10px]">orders</div>
                          <div className="text-emerald-400 font-semibold text-xs mt-0.5">✓ 100% (45M rows)</div>
                        </div>
                        <div className="p-2.5 rounded bg-zinc-900/60 border border-zinc-800">
                          <div className="text-zinc-400 text-[10px]">order_items</div>
                          <div className="text-indigo-400 font-semibold text-xs mt-0.5">● 88% (120M rows)</div>
                        </div>
                        <div className="p-2.5 rounded bg-zinc-900/60 border border-zinc-800">
                          <div className="text-zinc-400 text-[10px]">users</div>
                          <div className="text-emerald-400 font-semibold text-xs mt-0.5">✓ 100% (14M rows)</div>
                        </div>
                        <div className="p-2.5 rounded bg-zinc-900/60 border border-zinc-800">
                          <div className="text-zinc-400 text-[10px]">audit_logs</div>
                          <div className="text-zinc-500 font-semibold text-xs mt-0.5">⏱ Queued</div>
                        </div>
                      </div>

                      {/* Live Audit Log Feed */}
                      <div className="p-3.5 rounded-lg bg-zinc-950/80 border border-zinc-800 space-y-1.5 font-mono text-xs text-zinc-300">
                        <div className="text-zinc-500 text-[10px] uppercase font-bold tracking-wider mb-1">Execution Event Stream</div>
                        <div className="flex items-center space-x-2 text-emerald-400">
                          <Check className="w-3 h-3 shrink-0" />
                          <span>[10:42:01] Schema AST validated: 0 foreign key circularity locks detected</span>
                        </div>
                        <div className="flex items-center space-x-2 text-indigo-300">
                          <RefreshCw className="w-3 h-3 shrink-0 animate-spin" />
                          <span>[10:42:04] Keyset worker #4 flushed chunk range [98,400,000 .. 99,200,000]</span>
                        </div>
                        <div className="flex items-center space-x-2 text-zinc-400">
                          <ShieldCheck className="w-3 h-3 shrink-0 text-emerald-400" />
                          <span>[10:42:06] SHA256 checksum matched on table `users` (14,102,400 rows verified)</span>
                        </div>
                      </div>
                    </div>

                    {/* Stream Telemetry Sidebar */}
                    <div className="space-y-3 flex flex-col justify-between">
                      <div className="p-3.5 rounded-lg bg-zinc-950/60 border border-zinc-800">
                        <span className="text-zinc-400 text-xs block mb-1">Data Throughput</span>
                        <div className="text-xl font-mono font-bold text-white flex items-baseline justify-between">
                          <span>42.8 MB/s</span>
                          <span className="text-xs text-emerald-400 font-normal">Native Keyset</span>
                        </div>
                      </div>

                      <div className="p-3.5 rounded-lg bg-zinc-950/60 border border-zinc-800">
                        <span className="text-zinc-400 text-xs block mb-1">Checksum Parity</span>
                        <div className="text-xl font-mono font-bold text-emerald-400 flex items-baseline justify-between">
                          <span>100.00%</span>
                          <span className="text-xs text-zinc-400 font-normal">Bit-level match</span>
                        </div>
                      </div>

                      <div className="p-3.5 rounded-lg bg-zinc-900/50 border border-zinc-800">
                        <span className="text-zinc-300 text-xs font-semibold block mb-1">Transactional Safety</span>
                        <p className="text-xs text-zinc-400 leading-relaxed">
                          Keyset offsets checkpointed every 50ms. If a target network packet drops, the engine resumes without key collision.
                        </p>
                      </div>
                    </div>

                  </div>
                )}

                {/* TAB 2: AST SCHEMA DIFF */}
                {activeWorkbenchTab === 'schema' && (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between text-xs font-mono text-zinc-400 pb-2 border-b border-zinc-800">
                      <span className="text-indigo-400">Source: PostgreSQL DDL</span>
                      <span className="text-emerald-400">Target: Compiled MySQL 8.0 DDL</span>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 font-mono text-xs">
                      <div className="p-3.5 bg-zinc-950 rounded-lg border border-zinc-800 text-zinc-300 overflow-x-auto">
                        <pre className="leading-relaxed">{DIALECT_EXAMPLES['pg-mysql'].sourceCode}</pre>
                      </div>
                      <div className="p-3.5 bg-zinc-950 rounded-lg border border-zinc-800 text-emerald-300/90 overflow-x-auto">
                        <pre className="leading-relaxed">{DIALECT_EXAMPLES['pg-mysql'].targetCode}</pre>
                      </div>
                    </div>

                    <div className="p-3 bg-zinc-900/60 rounded-lg border border-zinc-800 text-xs text-zinc-400 flex flex-wrap gap-4">
                      <span className="text-zinc-200 font-semibold font-mono">AST Transformations:</span>
                      <span>• UUID → VARCHAR(36)</span>
                      <span>• JSONB → JSON</span>
                      <span>• INET → VARCHAR(45)</span>
                      <span>• TIMESTAMPTZ → DATETIME(6)</span>
                    </div>
                  </div>
                )}

                {/* TAB 3: PARITY & CHECKSUM MATRIX */}
                {activeWorkbenchTab === 'parity' && (
                  <div className="space-y-3 font-mono text-xs">
                    <div className="overflow-x-auto">
                      <table className="w-full text-left border-collapse">
                        <thead>
                          <tr className="border-b border-zinc-800 text-zinc-400 text-[11px]">
                            <th className="pb-2 font-medium">Table Name</th>
                            <th className="pb-2 font-medium">Source Count</th>
                            <th className="pb-2 font-medium">Target Count</th>
                            <th className="pb-2 font-medium">Row Parity</th>
                            <th className="pb-2 font-medium">SHA-256 Checksum</th>
                            <th className="pb-2 font-medium text-right">Status</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-zinc-800/60 text-zinc-300">
                          <tr>
                            <td className="py-2.5 font-semibold text-white">orders</td>
                            <td className="py-2.5">45,120,891</td>
                            <td className="py-2.5">45,120,891</td>
                            <td className="py-2.5 text-emerald-400">100.00%</td>
                            <td className="py-2.5 text-zinc-400">e8f4...3a19</td>
                            <td className="py-2.5 text-right text-emerald-400 font-semibold">VERIFIED</td>
                          </tr>
                          <tr>
                            <td className="py-2.5 font-semibold text-white">order_items</td>
                            <td className="py-2.5">120,402,110</td>
                            <td className="py-2.5">105,953,856</td>
                            <td className="py-2.5 text-indigo-400">88.00%</td>
                            <td className="py-2.5 text-zinc-400">streaming...</td>
                            <td className="py-2.5 text-right text-indigo-400 font-semibold">IN PROGRESS</td>
                          </tr>
                          <tr>
                            <td className="py-2.5 font-semibold text-white">users</td>
                            <td className="py-2.5">14,102,400</td>
                            <td className="py-2.5">14,102,400</td>
                            <td className="py-2.5 text-emerald-400">100.00%</td>
                            <td className="py-2.5 text-zinc-400">9c1b...77f2</td>
                            <td className="py-2.5 text-right text-emerald-400 font-semibold">VERIFIED</td>
                          </tr>
                          <tr>
                            <td className="py-2.5 font-semibold text-white">audit_logs</td>
                            <td className="py-2.5">56,365,643</td>
                            <td className="py-2.5">0</td>
                            <td className="py-2.5 text-zinc-500">0.00%</td>
                            <td className="py-2.5 text-zinc-500">pending</td>
                            <td className="py-2.5 text-right text-zinc-500">QUEUED</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}

              </div>
            </div>
          </motion.div>

        </div>
      </section>


      {/* ================= SUPPORTED DIALECT MATRIX ================= */}
      <section className="py-16 border-y border-zinc-800/80 bg-zinc-950/40">
        <div className="max-w-6xl mx-auto px-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-10">
            <div>
              <span className="font-mono text-xs font-semibold text-indigo-400 uppercase tracking-wider">Cross-Engine Support</span>
              <h2 className="text-xl md:text-2xl font-bold text-white mt-1">
                Any-to-any relational database migration.
              </h2>
            </div>
            <Link to="/docs" className="text-xs font-medium text-indigo-400 hover:text-indigo-300 flex items-center space-x-1">
              <span>View dialect compatibility specifications</span>
              <ChevronRight className="w-3.5 h-3.5" />
            </Link>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <div className="p-4 rounded-lg bg-zinc-900/60 border border-zinc-800">
              <div className="text-white font-semibold text-sm mb-1 flex items-center justify-between">
                <span>PostgreSQL</span>
                <span className="text-[10px] font-mono bg-zinc-800 text-zinc-300 px-1.5 py-0.5 rounded">14–17</span>
              </div>
              <p className="text-xs text-zinc-400">Full JSONB, UUID, enum types, partition ranges, and WAL CDC.</p>
            </div>

            <div className="p-4 rounded-lg bg-zinc-900/60 border border-zinc-800">
              <div className="text-white font-semibold text-sm mb-1 flex items-center justify-between">
                <span>MySQL / Aurora</span>
                <span className="text-[10px] font-mono bg-zinc-800 text-zinc-300 px-1.5 py-0.5 rounded">8.0+</span>
              </div>
              <p className="text-xs text-zinc-400">Keyset chunking, binlog replication, InnoDB engine optimization.</p>
            </div>

            <div className="p-4 rounded-lg bg-zinc-900/60 border border-zinc-800">
              <div className="text-white font-semibold text-sm mb-1 flex items-center justify-between">
                <span>SQL Server</span>
                <span className="text-[10px] font-mono bg-zinc-800 text-zinc-300 px-1.5 py-0.5 rounded">2017–2022</span>
              </div>
              <p className="text-xs text-zinc-400">IDENTITY sequences, DATETIME2 microsecond parity, pyodbc native.</p>
            </div>

            <div className="p-4 rounded-lg bg-zinc-900/60 border border-zinc-800">
              <div className="text-white font-semibold text-sm mb-1 flex items-center justify-between">
                <span>Oracle DB</span>
                <span className="text-[10px] font-mono bg-zinc-800 text-zinc-300 px-1.5 py-0.5 rounded">19c / 21c</span>
              </div>
              <p className="text-xs text-zinc-400">NUMBER types, sequences, PL/SQL trigger conversion assistance.</p>
            </div>
          </div>
        </div>
      </section>


      {/* ================= INTERACTIVE DIALECT CONVERTER SHOWCASE ================= */}
      <section className="py-20 px-6 max-w-6xl mx-auto w-full">
        <motion.div {...FADE_UP} className="mb-10 text-left">
          <span className="font-mono text-xs font-semibold text-indigo-400 uppercase tracking-wider">
            Abstract Syntax Tree Translation
          </span>
          <h2 className="text-2xl md:text-3xl font-bold text-white mt-1 mb-2">
            Compile-time DDL conversion without regex guesswork.
          </h2>
          <p className="text-sm text-zinc-400 max-w-2xl">
            Fluxline parses source DDL into a typed syntax tree, maps relational constraints, resolves foreign key dependencies, and emits clean target SQL.
          </p>
        </motion.div>

        {/* Dialect Selectors */}
        <div className="flex flex-wrap gap-2 mb-6">
          {Object.entries(DIALECT_EXAMPLES).map(([key, ex]) => (
            <button
              key={key}
              onClick={() => setActiveDialect(key)}
              className={`px-3.5 py-1.5 rounded-md text-xs font-mono font-medium transition-all border cursor-pointer ${
                activeDialect === key
                  ? 'bg-zinc-800 border-zinc-600 text-white shadow-sm'
                  : 'bg-zinc-900/80 border-zinc-800 text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800'
              }`}
            >
              {ex.title}
            </button>
          ))}
        </div>

        {/* Code Diff Container */}
        <motion.div 
          key={activeDialect}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className="rounded-xl border border-zinc-800 bg-[#0c0c10] shadow-xl overflow-hidden"
        >
          <div className="p-3.5 bg-zinc-900/70 border-b border-zinc-800 flex items-center justify-between text-xs font-mono text-zinc-400">
            <div className="flex items-center space-x-3">
              <span className="text-zinc-200">Source: <strong>{DIALECT_EXAMPLES[activeDialect].from}</strong></span>
              <span>➔</span>
              <span className="text-emerald-400">Target: <strong>{DIALECT_EXAMPLES[activeDialect].to}</strong></span>
            </div>
            <Link to="/sandbox" className="text-indigo-400 hover:text-indigo-300 font-sans font-medium flex items-center space-x-1">
              <span>Test custom DDL in SQL Lab</span>
              <ArrowUpRight className="w-3.5 h-3.5" />
            </Link>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-zinc-800">
            <div className="p-5 bg-zinc-950/60 font-mono text-xs leading-relaxed text-zinc-300 overflow-x-auto">
              <div className="text-[10px] text-zinc-500 uppercase font-bold tracking-wider mb-2">Source Dialect DDL</div>
              <pre><code>{DIALECT_EXAMPLES[activeDialect].sourceCode}</code></pre>
            </div>

            <div className="p-5 bg-zinc-950/90 font-mono text-xs leading-relaxed text-emerald-300/90 overflow-x-auto">
              <div className="text-[10px] text-emerald-500 uppercase font-bold tracking-wider mb-2">Translated Target DDL</div>
              <pre><code>{DIALECT_EXAMPLES[activeDialect].targetCode}</code></pre>
            </div>
          </div>

          <div className="p-4 bg-zinc-900/40 border-t border-zinc-800 text-xs">
            <h4 className="text-zinc-400 font-semibold font-mono text-[11px] uppercase tracking-wider mb-2">Dialect Specifics Handled:</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-zinc-300 font-mono text-[11px]">
              {DIALECT_EXAMPLES[activeDialect].notes.map((note, idx) => (
                <div key={idx} className="flex items-center space-x-2">
                  <div className="w-1 h-1 rounded-full bg-indigo-400" />
                  <span>{note}</span>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </section>


      {/* ================= PERFORMANCE BENCHMARKS TABLE ================= */}
      <section className="py-16 border-y border-zinc-800/80 bg-zinc-950/40">
        <div className="max-w-6xl mx-auto px-6">
          <div className="mb-8">
            <span className="font-mono text-xs font-semibold text-indigo-400 uppercase tracking-wider">Engine Performance</span>
            <h2 className="text-2xl font-bold text-white mt-1">
              Throughput benchmarked on production datasets.
            </h2>
            <p className="text-xs text-zinc-400 mt-1">
              Measured using Keyset Streaming vs standard OFFSET paging vs native pgloader across AWS RDS instances.
            </p>
          </div>

          <div className="rounded-xl border border-zinc-800 bg-[#0e0e12] overflow-hidden">
            <table className="w-full text-left border-collapse font-mono text-xs">
              <thead>
                <tr className="bg-zinc-900/80 border-b border-zinc-800 text-zinc-400 text-[11px]">
                  <th className="p-3.5 font-medium">Migration Pair</th>
                  <th className="p-3.5 font-medium">Dataset Size</th>
                  <th className="p-3.5 font-medium">Streaming Mode</th>
                  <th className="p-3.5 font-medium">Throughput Rate</th>
                  <th className="p-3.5 font-medium text-right">Elapsed Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60 text-zinc-300">
                <tr>
                  <td className="p-3.5 text-white font-semibold">MySQL 8 ➔ PostgreSQL 16</td>
                  <td className="p-3.5">200,000 rows</td>
                  <td className="p-3.5 text-indigo-400">pgloader (WSL native)</td>
                  <td className="p-3.5 text-emerald-400 font-semibold">27,397 rows/sec</td>
                  <td className="p-3.5 text-right font-semibold text-zinc-100">7.3 sec</td>
                </tr>
                <tr>
                  <td className="p-3.5 text-white font-semibold">SQL Server ➔ PostgreSQL 16</td>
                  <td className="p-3.5">200,000 rows</td>
                  <td className="p-3.5 text-indigo-400">pgloader (WSL native)</td>
                  <td className="p-3.5 text-emerald-400 font-semibold">24,540 rows/sec</td>
                  <td className="p-3.5 text-right font-semibold text-zinc-100">8.1 sec</td>
                </tr>
                <tr>
                  <td className="p-3.5 text-white font-semibold">SQL Server ➔ MySQL 8.0</td>
                  <td className="p-3.5">200,000 rows</td>
                  <td className="p-3.5 text-sky-400">Keyset Streaming (Parallel)</td>
                  <td className="p-3.5 text-emerald-400 font-semibold">10,800 rows/sec</td>
                  <td className="p-3.5 text-right font-semibold text-zinc-100">18.5 sec</td>
                </tr>
                <tr>
                  <td className="p-3.5 text-white font-semibold">PostgreSQL ➔ MySQL 8.0</td>
                  <td className="p-3.5">1,000,000 rows</td>
                  <td className="p-3.5 text-sky-400">Keyset Streaming (Parallel)</td>
                  <td className="p-3.5 text-emerald-400 font-semibold">34,200 rows/sec</td>
                  <td className="p-3.5 text-right font-semibold text-zinc-100">29.2 sec</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>


      {/* ================= 6 CORE ENGINEERING PILLARS ================= */}
      <section className="py-20 px-6 max-w-6xl mx-auto" id="features">
        <motion.div {...FADE_UP} className="mb-12 text-left">
          <span className="font-mono text-xs font-semibold text-indigo-400 uppercase tracking-wider">Architecture</span>
          <h2 className="text-2xl md:text-3xl font-bold text-white mt-1">
            Engineered for production database reliability.
          </h2>
          <p className="text-sm text-zinc-400 mt-1 max-w-2xl">
            Built from first principles to avoid the subtle traps of cross-database cutovers.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
          
          <motion.div {...FADE_UP} className="p-5 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-all flex flex-col justify-between">
            <div>
              <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 mb-4">
                <ShieldCheck className="w-4 h-4" />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">Dry-Run Pre-flight Checks</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Compile schemas and sample data passes without touching production targets. Inspect constraint mismatches, column truncations, and missing types before applying changes.
              </p>
            </div>
          </motion.div>

          <motion.div {...FADE_UP} className="p-5 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-all flex flex-col justify-between">
            <div>
              <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400 mb-4">
                <Zap className="w-4 h-4" />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">Keyset Chunking Stream</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Avoids slow <code className="text-zinc-200">OFFSET</code> paging that degrades on deep tables. Uses deterministic indexed ranges for sustained 30,000+ rows/sec throughput without locking source tables.
              </p>
            </div>
          </motion.div>

          <motion.div {...FADE_UP} className="p-5 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-all flex flex-col justify-between">
            <div>
              <div className="w-8 h-8 rounded-lg bg-sky-500/10 border border-sky-500/20 flex items-center justify-center text-sky-400 mb-4">
                <Network className="w-4 h-4" />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">FK Dependency Sequencing</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Constructs a directed acyclic graph (DAG) of all foreign key relationships to automatically migrate parent tables before dependent children, preventing constraint deadlocks.
              </p>
            </div>
          </motion.div>

          <motion.div {...FADE_UP} className="p-5 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-all flex flex-col justify-between">
            <div>
              <div className="w-8 h-8 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-center justify-center text-amber-400 mb-4">
                <BarChart3 className="w-4 h-4" />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">Byte-Level Checksums</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Computes cryptographic hash digests across source and target tables to confirm zero bit rot, truncation, or encoding corruption after cutover completion.
              </p>
            </div>
          </motion.div>

          <motion.div {...FADE_UP} className="p-5 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-all flex flex-col justify-between">
            <div>
              <div className="w-8 h-8 rounded-lg bg-rose-500/10 border border-rose-500/20 flex items-center justify-center text-rose-400 mb-4">
                <Layers className="w-4 h-4" />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">Transactional Rollback</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Target table states are tracked with exact commit offsets. If a network interruption occurs, the engine resumes cleanly without requiring a full restart.
              </p>
            </div>
          </motion.div>

          <motion.div {...FADE_UP} className="p-5 rounded-xl bg-zinc-900/50 border border-zinc-800 hover:border-zinc-700 transition-all flex flex-col justify-between">
            <div>
              <div className="w-8 h-8 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center text-purple-400 mb-4">
                <Terminal className="w-4 h-4" />
              </div>
              <h3 className="text-sm font-semibold text-white mb-2">GitOps CLI & CI/CD</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Automate schema diffing and ephemeral staging database teardowns directly in GitHub Actions or GitLab CI using the lightweight Fluxline CLI.
              </p>
            </div>
          </motion.div>

        </div>
      </section>


      {/* ================= CLI & DEVELOPER WORKFLOW ================= */}
      <section className="py-16 border-y border-zinc-800/80 bg-zinc-950/40">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
            
            <motion.div {...FADE_UP}>
              <span className="font-mono text-xs font-semibold text-indigo-400 uppercase tracking-wider">Developer Workflows</span>
              <h2 className="text-2xl font-bold text-white mt-1 mb-3">
                Run via web console, CLI, or CI/CD pipelines.
              </h2>
              <p className="text-xs text-zinc-400 mb-6 leading-relaxed">
                Use the web UI for interactive visual migrations, or embed Fluxline in your deployment scripts for repeatable, automated database syncs.
              </p>

              <div className="space-y-2 text-xs font-mono text-zinc-300 mb-6">
                <div className="flex items-center space-x-2">
                  <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                  <span>Supports JSON config files & environment variables</span>
                </div>
                <div className="flex items-center space-x-2">
                  <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                  <span>Exportable audit reports in Markdown and JSON</span>
                </div>
                <div className="flex items-center space-x-2">
                  <CheckCircle className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                  <span>REST API for ephemeral staging branch replication</span>
                </div>
              </div>

              <div className="flex items-center space-x-3">
                <Link to="/docs" className="px-4 py-2 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-white font-sans text-xs font-semibold border border-zinc-700 transition-all flex items-center space-x-1.5">
                  <Terminal className="w-3.5 h-3.5" />
                  <span>Read CLI Documentation</span>
                </Link>
              </div>
            </motion.div>

            {/* Terminal Box */}
            <motion.div {...FADE_UP}>
              <div className="rounded-xl border border-zinc-800 bg-[#09090d] shadow-2xl overflow-hidden font-mono text-xs">
                <div className="h-9 bg-zinc-900/80 border-b border-zinc-800 flex items-center justify-between px-3.5">
                  <div className="flex items-center space-x-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-zinc-700" />
                    <div className="w-2.5 h-2.5 rounded-full bg-zinc-700" />
                    <div className="w-2.5 h-2.5 rounded-full bg-zinc-700" />
                    <span className="text-zinc-500 text-[11px] ml-2">fluxline-cli</span>
                  </div>
                  <button 
                    onClick={copyCliCommand}
                    className="text-[11px] text-zinc-400 hover:text-white flex items-center space-x-1 bg-zinc-800 px-2 py-0.5 rounded border border-zinc-700 transition-colors cursor-pointer"
                  >
                    {copiedCli ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                    <span>{copiedCli ? 'Copied' : 'Copy'}</span>
                  </button>
                </div>
                <div className="p-5 text-zinc-300 leading-relaxed space-y-2">
                  <div className="text-zinc-500"># Verify schema & estimate throughput</div>
                  <div>
                    <span className="text-indigo-400 font-bold">$</span> npx @fluxline/cli verify \<br/>
                    &nbsp;&nbsp;--source "postgres://app_user:secret@db-prod.internal:5432/primary" \<br/>
                    &nbsp;&nbsp;--target "mysql://db_admin:secret@aurora-cluster:3306/replica"
                  </div>
                  <div className="pt-2 text-zinc-400 space-y-0.5">
                    <div>[1/3] Parsing source DDL AST... <span className="text-emerald-400">Done (124 tables)</span></div>
                    <div>[2/3] Resolving FK DAG sequences... <span className="text-emerald-400">0 circular locks</span></div>
                    <div>[3/3] Checking type compatibility... <span className="text-emerald-400">100% compliant</span></div>
                  </div>
                  <div className="pt-2 text-emerald-400 font-semibold">
                    ✓ Pre-flight passed: Ready for live keyset stream.
                  </div>
                </div>
              </div>
            </motion.div>

          </div>
        </div>
      </section>


      {/* ================= REAL INFRASTRUCTURE CASE STUDIES ================= */}
      <section className="py-20 px-6 max-w-6xl mx-auto">
        <div className="mb-12 text-left">
          <span className="font-mono text-xs font-semibold text-indigo-400 uppercase tracking-wider">Field Proven</span>
          <h2 className="text-2xl font-bold text-white mt-1">
            Proven on mission-critical production cutovers.
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="p-6 rounded-xl bg-zinc-900/40 border border-zinc-800 flex flex-col justify-between">
            <p className="text-xs text-zinc-300 leading-relaxed mb-6">
              "We had to migrate 180 million rows from legacy PostgreSQL to Aurora MySQL for a multi-tenant client. Fluxline caught 3 subtle enum gotchas during pre-flight dry-run and finished the live cutover with zero application downtime."
            </p>
            <div className="pt-4 border-t border-zinc-800/80">
              <div className="text-xs font-semibold text-white">Data Infrastructure Architect</div>
              <div className="text-[11px] text-zinc-500 font-mono">Fintech Ledger System</div>
            </div>
          </div>

          <div className="p-6 rounded-xl bg-zinc-900/40 border border-zinc-800 flex flex-col justify-between">
            <p className="text-xs text-zinc-300 leading-relaxed mb-6">
              "The AST translation alone saved our data engineering team weeks of writing manual mapping scripts. SQL Server IDENTITY sequences and DATETIME2 columns mapped to PostgreSQL with exact millisecond accuracy."
            </p>
            <div className="pt-4 border-t border-zinc-800/80">
              <div className="text-xs font-semibold text-white">Principal Systems Engineer</div>
              <div className="text-[11px] text-zinc-500 font-mono">B2B SaaS Platform</div>
            </div>
          </div>

          <div className="p-6 rounded-xl bg-zinc-900/40 border border-zinc-800 flex flex-col justify-between">
            <p className="text-xs text-zinc-300 leading-relaxed mb-6">
              "The cryptographic checksum verification was essential for our SOC2 audit. We had an exact row count and hash parity report for all 140 tables signed off in minutes."
            </p>
            <div className="pt-4 border-t border-zinc-800/80">
              <div className="text-xs font-semibold text-white">Staff DevOps Lead</div>
              <div className="text-[11px] text-zinc-500 font-mono">E-Commerce Infrastructure</div>
            </div>
          </div>
        </div>
      </section>


      {/* ================= TECHNICAL FAQ ================= */}
      <section className="py-16 border-t border-zinc-800/80 max-w-4xl mx-auto px-6">
        <div className="mb-10 text-left">
          <h2 className="text-xl md:text-2xl font-bold text-white mb-2">
            Technical FAQ
          </h2>
          <p className="text-xs text-zinc-400">
            Details on security, connection isolation, and transactional safety.
          </p>
        </div>

        <div className="space-y-4">
          {[
            {
              q: "Does Fluxline write to or lock source production tables?",
              a: "No. Fluxline connects to the source database strictly using read-only permissions with repeatable-read isolation or binary log streaming (WAL / binlog). Source tables are never locked."
            },
            {
              q: "How does keyset chunking handle tables with millions of rows?",
              a: "Instead of OFFSET paging which forces the database engine to scan and discard rows, Fluxline queries indexed primary keys (e.g., WHERE id > :last_id LIMIT 10000). This delivers consistent sub-10ms chunk fetches regardless of table depth."
            },
            {
              q: "What happens if a network interruption occurs mid-migration?",
              a: "Fluxline continuously commits state checkpoints. Upon reconnection, it queries target table high-water marks and resumes from the exact offset, preventing duplicates or constraint errors."
            },
            {
              q: "Can I run a dry-run test without inserting data into target?",
              a: "Yes. In dry-run mode, schemas are translated and checked in a temporary target schema with zero-row insertions to verify syntax and constraint validity."
            }
          ].map((item, idx) => (
            <div key={idx} className="p-5 rounded-lg bg-zinc-900/40 border border-zinc-800">
              <h3 className="text-xs font-semibold text-white mb-1.5">{item.q}</h3>
              <p className="text-xs text-zinc-400 leading-relaxed">{item.a}</p>
            </div>
          ))}
        </div>
      </section>


      {/* ================= READY TO MIGRATE CTA ================= */}
      <section className="py-16 px-6 relative z-10">
        <div className="max-w-4xl mx-auto rounded-2xl bg-zinc-900/80 border border-zinc-800 p-8 md:p-12 text-center relative overflow-hidden shadow-xl">
          <h2 className="text-2xl md:text-3xl font-bold text-white mb-3 tracking-tight">
            Ready to execute a deterministic migration?
          </h2>
          <p className="text-xs md:text-sm text-zinc-400 mb-6 max-w-xl mx-auto leading-relaxed">
            Connect your databases, inspect compiled schema mappings, and verify data parity in minutes.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <Link 
              to="/app/new" 
              className="w-full sm:w-auto px-6 py-3 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-sans text-sm font-semibold transition-all shadow-sm flex items-center justify-center space-x-2"
            >
              <span>Start Migration</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
            <Link 
              to="/sandbox" 
              className="w-full sm:w-auto px-6 py-3 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-sans text-sm font-medium border border-zinc-700 transition-all flex items-center justify-center space-x-2"
            >
              <span>Open SQL Lab</span>
            </Link>
          </div>
        </div>
      </section>

    </div>
  )
}
