
ALTER USER 'root'@'localhost' IDENTIFIED BY 'Ayaz@123';
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'Ayaz@123';
ALTER USER 'root'@'%' IDENTIFIED BY 'Ayaz@123';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
